#pragma once

#include <iostream>
#include <fstream>
#include <vector>
#include <cmath>
#include <iomanip>
#include <set>
#include <random>
#include <string>

#include <ql/quantlib.hpp>
#include <ql/processes/hestonprocess.hpp>
#include <ql/processes/hullwhiteprocess.hpp>
#include <ql/processes/hybridhestonhullwhiteprocess.hpp>

#include "callPrice.cpp"

using namespace std;
using namespace QuantLib;

class generateData{
private:
    // number of days we will be going ahead
    int time_steps;

    // first let us define the heston parameters and other necessary constants
    double S0, v0, mu, kappa_P, theta_P, xi, rho, r, q, lambda;

    // we need to keep track of the evolution of S, v, r across time
    vector<double> S, v, rates;

    // We need to keep track of evolution of parameters across time
    vector<vector<double>> params;

    // the set of moneyness and maturities whose options we will be creating
    vector<double> moneyness_values;

    // number of time parameters jump in an year
    int jump_intensity;

    string today;

    // Grid for each time steps
    // for each day we have a grid
    // each grid consists of tuples
    // each tuple have strike, maturity, C_price/vol
    vector<vector<vector<double>>> C_grid, vol_grid;

    // store actual expiry dates just in case
    vector<vector<QuantLib::Date>> expiry_date_grid;

    // We need to keep track of which options are expiring so we can generate more of them
    set<QuantLib::Date> weekly_expiry, monthly_expiry;

    // helper function which takes quantlib's date and converts it into dd-mmm-yyyy
    string dateToString(const QuantLib::Date& date) {
        static const array<string, 12> months = {
            "Jan", "Feb", "Mar", "Apr", "May", "Jun",
            "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
        };

        ostringstream oss;

        oss << setfill('0')
            << setw(2) << date.dayOfMonth()
            << "-"
            << months[static_cast<int>(date.month()) - 1]
            << "-"
            << date.year();

        return oss.str();
    }

    // helper function which checks the current day and gives the next friday
    // if next friday is not available, then we use a previous working day
    QuantLib::Date getNextFridayOrPreviousBusinessDay(const QuantLib::Date& today,
                                                    const QuantLib::Calendar& cal) {

        QuantLib::Date d = today;

        // Move forward until Friday
        while (d.weekday() != QuantLib::Friday) {
            d = d + 1;
        }

        // If Friday is holiday, move to previous business day
        d = cal.adjust(d, QuantLib::Preceding);

        return d;
    }

    // similarly get the value for end of month expiry options
    QuantLib::Date getEndOfMonthExpiry(const QuantLib::Date& date, const QuantLib::Calendar& cal) {

        QuantLib::Date eom = QuantLib::Date::endOfMonth(date);
        return cal.adjust(eom, QuantLib::Preceding);
    }

    double impliedVolFromCallPrice(double CallPrice, double S0, double K, double T, double r, double q){
        
        if (T <= 0.0) throw invalid_argument("T <= 0.0");
        
        double discount = exp(-r * T);
        double forward = S0 * exp((r-q)*T);

        double guessStdDev = 0.2 * sqrt(T);

        double stdDev = blackFormulaImpliedStdDev(
            QuantLib::Option::Call,
            K,
            forward,
            CallPrice,
            discount,
            0.0,
            guessStdDev,
            1e-8,     // accuracy
            200      // max iterations
        );
        return stdDev / sqrt(T);
    }

    // A function to evolve parameters of heston
    vector<double> evolveParametersOUJump(const vector<double>& params, double dt, mt19937& gen, double jump_intensity, normal_distribution<double> normal) {
        poisson_distribution<int> poisson(jump_intensity * dt);

        vector<double> x(6);

        // transform into unconstrained space
        x[0] = params[0];                  // mu
        x[1] = log(params[1]);             // kappa_P
        x[2] = log(params[2]);             // theta_P
        x[3] = log(params[3]);             // xi
        x[4] = atanh(max(-0.999, min(0.999, params[4]))); // rho
        x[5] = log(params[5]);             // lambda

        // [TODO] - check, generated by ChatGPT
        vector<double> a = {1.0, 1.5, 1.5, 1.2, 1.0, 1.0};

        vector<double> base_sigma = {0.02, 0.20, 0.15, 0.15, 0.20, 0.20};

        vector<double> beta = {0.5, 0.4, 0.4, 0.4, 0.3, 0.4};

        vector<double> vol_randomness = {0.25, 0.25, 0.25, 0.25, 0.20, 0.25};

        vector<double> jump_mean_std = {0.03, 0.35, 0.30, 0.30, 0.35, 0.35};

        vector<double> jump_sigma_base = {0.04, 0.45, 0.35, 0.35, 0.45, 0.45};

        // approximate as bernoulli
        bool has_jump = poisson(gen) > 0;

        for (int i = 0; i < 6; i++) {
            double sigma_t = base_sigma[i] * (1.0 + beta[i] * abs(x[i])) * exp(vol_randomness[i] * normal(gen));

            if (!has_jump) {
                x[i] += -a[i] * x[i] * dt + sigma_t * sqrt(dt) * normal(gen);
            } else {
                double random_mean = jump_mean_std[i] * normal(gen);

                double jump_sigma = jump_sigma_base[i] * exp(0.30 * normal(gen));

                double jump_size = random_mean + jump_sigma * normal(gen);

                x[i] += a[i] * (random_mean - x[i]) * dt + jump_sigma * sqrt(dt) * normal(gen) + jump_size;
            }
        }

        vector<double> next(6);

        // get back to constrained space
        next[0] = x[0];
        next[1] = exp(x[1]);
        next[2] = exp(x[2]);
        next[3] = exp(x[3]);
        next[4] = tanh(x[4]);
        next[5] = exp(x[5]);

        return next;
    }

    // function to simulate the rate of interest using Hull-White
    void simulate_r(double r0, int no_of_timesteps, vector<double>& rates, const QuantLib::Date& todayDate) {
        // Hull-White parameters
        double a_r = 0.10;      // mean reversion speed
        double sigma_r = 0.01;  // short-rate volatility

        // Time step: daily trading step
        double dt = 1.0 / 252.0;

        // Set QuantLib evaluation date
        QuantLib::Settings::instance().evaluationDate() = todayDate;

        QuantLib::DayCounter dc = QuantLib::Actual365Fixed();

        // Initial flat yield curve
        QuantLib::Handle<QuantLib::YieldTermStructure> yieldCurve(
            QuantLib::ext::make_shared<QuantLib::FlatForward>(
                todayDate,
                r0,
                dc
            )
        );

        // QuantLib Hull-White short-rate process
        QuantLib::HullWhiteProcess hwProcess(
            yieldCurve,
            a_r,
            sigma_r
        );

        // Random generator
        random_device rd;
        mt19937 gen(rd());
        normal_distribution<double> normal(0.0, 1.0);

        double r = r0;
        double t = 0.0;

        for (int i = 1; i <= no_of_timesteps; i++) {
            double z = normal(gen);

            // QuantLib expects z ~ N(0,1)
            r = hwProcess.evolve(t, r, dt, z);

            t += dt;
            rates[i] = r;
        }
    }

    // function to evolve the heston parameters
    pair<double, double> evolve_heston_one_step(double S_prev, double v_prev, double r, double q, double kappa, double theta, double xi, double rho, double dt, const QuantLib::Date& todayDate, normal_distribution<double>& normal, mt19937& gen) {
        QuantLib::Settings::instance().evaluationDate() = todayDate;

        QuantLib::DayCounter dc = Actual365Fixed();

        QuantLib::Handle<QuantLib::YieldTermStructure> riskFreeTS(QuantLib::ext::make_shared<FlatForward>(todayDate, r, dc));

        QuantLib::Handle<QuantLib::YieldTermStructure> dividendTS(QuantLib::ext::make_shared<FlatForward>(todayDate, q, dc));

        QuantLib::Handle<QuantLib::Quote> spot(QuantLib::ext::make_shared<QuantLib::SimpleQuote>(S_prev));

        double v0 = max(v_prev, 1e-12);

        QuantLib::HestonProcess process(
            riskFreeTS,
            dividendTS,
            spot,
            v0,
            kappa,
            theta,
            xi,
            rho,
            QuantLib::HestonProcess::QuadraticExponentialMartingale
        );

        QuantLib::Array x0(2);
        x0[0] = S_prev;
        x0[1] = v0;

        QuantLib::Array dw(2);
        dw[0] = normal(gen);  // independent N(0,1)
        dw[1] = normal(gen);  // independent N(0,1)

        QuantLib::Time t = 0.0;

        QuantLib::Array x1 = process.evolve(t, x0, dt, dw);

        return {
            x1[0],
            max<double>(x1[1], 1e-12)
        };
    }

public:
    // Here we will initialize all the values
    generateData(){
        time_steps = 12000;         // the number of timesteps we want to go ahead from

        // on average parameters jump once every week
        jump_intensity = 52;

        // we declare the initial values of parameters
        S0 = 100.0, v0 = 0.04, mu = 0.05, kappa_P = 1.5, theta_P = 0.04, xi = 0.3, rho = -0.7, r = 0.03, q = 0.00, lambda = 0.50;

        // push the current values of S and v
        S.resize(time_steps+1);
        v.resize(time_steps+1);
        params.resize(time_steps+1);
        rates.resize(time_steps+1);
        C_grid.resize(time_steps+1);
        vol_grid.resize(time_steps+1);
        expiry_date_grid.resize(time_steps+1);

        S[0] = S0;
        v[0] = v0;
        params[0] = {mu, kappa_P, theta_P, xi, rho, lambda};
        rates[0] = r;

        // decide the moneylessness values
        moneyness_values = {0.8, 0.85, 0.9, 0.95, 1, 1.05, 1.1, 1.15, 1.2};

        today = "2010-01-01";
        QuantLib::Date initialDate = QuantLib::DateParser::parseISO(today);
        QuantLib::Calendar cal = QuantLib::TARGET();
        QuantLib::DayCounter dayCounter = QuantLib::Actual365Fixed();

        if (!cal.isBusinessDay(initialDate)) {
           initialDate = cal.adjust(initialDate, QuantLib::Following);
           cout << "The provided start date was not a working date!\nStarting on date: " << initialDate << '\n';
        }

        // then we also simulate the entire rate
        simulate_r(rates[0], time_steps, rates, initialDate);

        // we also need the call options grid / volatility grid at time t=0

        // first let us start by weekly expiries
        QuantLib::Date expiry_date = initialDate;

        double kappa_Q = kappa_P + lambda;
        double theta_Q = kappa_P * theta_P / (kappa_P + lambda);

        normal_distribution<double> normal(0.0, 1.0);

        // get the next 5 weeks expiries
        for(int week = 0 ; week < 5 ; week++){
            expiry_date = getNextFridayOrPreviousBusinessDay(expiry_date, cal);

            // add entry to the expiries
            weekly_expiry.insert(expiry_date);

            // we add the values of strike prices for this
            for(auto m : moneyness_values){
                // we want weekly and monthly expiries
                double strike_price = m * S[0];
                double time_to_maturity = dayCounter.yearFraction(initialDate, expiry_date);
                    
                try
                {
                    double call_option_price = qe::hestonCallPrice(S[0], strike_price, time_to_maturity, r, q, v[0], kappa_Q, theta_Q, xi, rho, initialDate);
                    double imp_vol = impliedVolFromCallPrice(call_option_price, S[0], strike_price, time_to_maturity, r, q);
                    C_grid[0].push_back({strike_price, time_to_maturity, call_option_price});
                    vol_grid[0].push_back({strike_price, time_to_maturity, imp_vol});
                    expiry_date_grid[0].push_back(expiry_date);
                }
                catch(const QuantLib::Error& e)
                {
                    // if price goes negative, we just ignore it
                    continue;
                }
            }

            expiry_date = expiry_date + 7;    // move by 7 calendar days to go to next week
        }

        // Next we start monthly 
        expiry_date = initialDate;       // reset the expiry_date

        for(int month = 0 ; month < 12 ; month++){
            expiry_date = getEndOfMonthExpiry(expiry_date, cal);

            // add entry to the expiries
            monthly_expiry.insert(expiry_date);

            // if this were already done in weekly, then we skip
            if(weekly_expiry.find(expiry_date) != weekly_expiry.end()){
                // move ahead by one business day
                expiry_date = cal.advance(expiry_date, 1, QuantLib::Days);
                continue;
            }

            // we add the values of strike prices for this
            for(auto m : moneyness_values){
                // we want weekly and monthly expiries
                double strike_price = m * S[0];
                double time_to_maturity = dayCounter.yearFraction(initialDate, expiry_date);
                    
                try
                {
                    double call_option_price = qe::hestonCallPrice(S[0], strike_price, time_to_maturity, rates[0], q, v[0], kappa_Q, theta_Q, xi, rho, initialDate);
                    double imp_vol = impliedVolFromCallPrice(call_option_price, S[0], strike_price, time_to_maturity, rates[0], q);
                    C_grid[0].push_back({strike_price, time_to_maturity, call_option_price});
                    vol_grid[0].push_back({strike_price, time_to_maturity, imp_vol});
                    expiry_date_grid[0].push_back(expiry_date);
                }
                catch(const QuantLib::Error& e)
                {
                    // if price goes negative, we just ignore it
                    continue;
                }
            }

            expiry_date = cal.advance(expiry_date, 1, QuantLib::Days);
        }

        // now that we have the initial values, we will go through time and generate the data for each time stamp
        mt19937 gen(random_device{}());
        QuantLib::Date cur_date = initialDate;

        for(int t = 1 ; t <= time_steps ; t++){
            // we first advance by one business day
            cur_date = cal.advance(cur_date, 1, QuantLib::Days);

            // evolve parameters
            params[t] = evolveParametersOUJump(params[t-1], 1/252.0, gen, jump_intensity, normal);

            // evolve volatility and stock price using heston
            double kappa_Q = params[t][1] + params[t][5];
            double theta_Q = params[t][1] * params[t][2] / (params[t][1] + params[t][5]);
            auto evolve_s_v = evolve_heston_one_step(S[t-1], v[t-1], rates[t], q, kappa_Q, theta_Q, params[t][3], params[t][4], 1/252.0, cur_date, normal, gen);
            S[t] = evolve_s_v.first;
            v[t] = evolve_s_v.second;

            // if something is expring today, we need to ensure that we create a new option for that
            if(weekly_expiry.find(cur_date) != weekly_expiry.end()){ 
                weekly_expiry.erase(cur_date);

                // need to go 5 weeks ahead and friday
                QuantLib::Date expiry_date = cur_date + 35;
                expiry_date = getNextFridayOrPreviousBusinessDay(expiry_date, cal);

                weekly_expiry.insert(expiry_date);
            }

            // monthly_expiry;
            if(monthly_expiry.find(cur_date) != monthly_expiry.end()){ 
                monthly_expiry.erase(cur_date);

                // need to go 12 months ahead and end of month
                QuantLib::Date expiry_date = cur_date;
                for(int i = 0 ; i < 11 ; i++){
                    expiry_date = getEndOfMonthExpiry(expiry_date, cal);
                    expiry_date = cal.advance(expiry_date, 1, QuantLib::Days);
                }
                expiry_date = getEndOfMonthExpiry(expiry_date, cal);
                monthly_expiry.insert(expiry_date);
            }

            // for the remaining just add the values as required
            for(auto expiry_date : weekly_expiry){
                for(auto m : moneyness_values){
                    // we want weekly and monthly expiries
                    double strike_price = m * S[t];
                    double time_to_maturity = dayCounter.yearFraction(cur_date, expiry_date);
                        
                    try
                    {
                        double call_option_price = qe::hestonCallPrice(S[t], strike_price, time_to_maturity, rates[t], q, v[t], kappa_Q, theta_Q, xi, rho, cur_date);
                        double imp_vol = impliedVolFromCallPrice(call_option_price, S[t], strike_price, time_to_maturity, rates[t], q);
                        C_grid[t].push_back({strike_price, time_to_maturity, call_option_price});
                        vol_grid[t].push_back({strike_price, time_to_maturity, imp_vol});
                        expiry_date_grid[t].push_back(expiry_date);
                    }
                    catch(const QuantLib::Error& e)
                    {
                        // if price goes negative, we just ignore it
                        continue;
                    }
                }                
            }

            for(auto expiry_date : monthly_expiry){
                // ensure it was not already done before
                if(weekly_expiry.find(expiry_date) != weekly_expiry.end()) continue;

                for(auto m : moneyness_values){
                    // we want weekly and monthly expiries
                    double strike_price = m * S[t];
                    double time_to_maturity = dayCounter.yearFraction(cur_date, expiry_date);
                        
                    try
                    {
                        double call_option_price = qe::hestonCallPrice(S[t], strike_price, time_to_maturity, rates[t], q, v[t], kappa_Q, theta_Q, xi, rho, cur_date);
                        double imp_vol = impliedVolFromCallPrice(call_option_price, S[t], strike_price, time_to_maturity, rates[t], q);
                        C_grid[t].push_back({strike_price, time_to_maturity, call_option_price});
                        vol_grid[t].push_back({strike_price, time_to_maturity, imp_vol});
                        expiry_date_grid[t].push_back(expiry_date);
                    }
                    catch(const QuantLib::Error& e)
                    {
                        // if price goes negative, we just ignore it
                        continue;
                    }
                }                
            }
        }

        // finally we print the data
        ofstream data("./Data_Output/C_data.csv"), parameters("./Data_Output/heston_params.csv");
        data << "date,expiry date,strike,maturity (years),rate,underlying,call option price,implied vol\n";
        parameters << "date,mu,kappa_P,theta_P,xi,rho,lambda\n";
        cur_date = initialDate;
        for(int t = 0 ; t <= time_steps ; t++){
            string print_date = dateToString(cur_date);
            for(int entry = 0 ; entry < C_grid[t].size() ; entry++){
                string print_expiry_date = dateToString(expiry_date_grid[t][entry]);
                data << print_date << ',' << print_expiry_date << ',' << C_grid[t][entry][0] << ',' 
                << C_grid[t][entry][1] << ',' 
                << rates[t]*100.0 << ',' << S[t] << ',' 
                << C_grid[t][entry][2] << ',' 
                << vol_grid[t][entry][2] 
                << '\n';
            }

            parameters << print_date << ',' << params[t][0] << ',' << params[t][1] << ',' << params[t][2] << ',' << params[t][3] << ',' << params[t][4] << ',' << params[t][5] << ',' << '\n';
            // advance one timestep forward
            cur_date = cal.advance(cur_date, 1, Days);
        }
        data.close();
        parameters.close();
    }
};